# Query: Get a specific character by ID
query GetCharacter($charId: Int!) {
  character(char_id: $charId) {
    char_id
    name
    birthday
    status
    occupation
    portrayed
    nickname
    votes
    img
  }
}

# Variables:
# {
#   "charId": 1
# }
