query GetTwoCharacters($walterId: Int!, $jessieId: Int! ) {
  walter: character(char_id: $walterId) {
    char_id
    ...personajesFragment
  }

  jessie: character(char_id: $jessieId) {
    char_id
    name
    birthday
    occupation
    img
    status
    nickname
    appearance
    portrayed
    category
    better_call_saul_appearance
    votes
  }
  
}

fragment personajesFragment on Character{
  name
  birthday
  occupation
  img
  status
  nickname
  appearance
  portrayed
  category
  better_call_saul_appearance
  votes

}

