# Subscription: Real-time vote updates
subscription OnVoteUpdated {
  voteUpdated {
    vote {
      id
      character_name
      voted_at
    }
    character {
      char_id
      name
      votes
    }
    totalVotes
  }
}
