# Mutation: Vote for a character
mutation VoteForCharacter($charId: Int!) {
  voteForCharacter(char_id: $charId) {
    id
    char_id
    character_name
    voted_at
  }
}

# Variables:
# {
#   "charId": 1
# }
